Editing some conventions (#11)
* Add the samples file folder for the prototypes

This is a prototype sample. 
So it may not be run successfully but requires further functions wrapped which are the essential utilities of MAGMA and have not been finished yet.

* GSoC MAGMA binding Proposal v1.1

* Delete samples.jl

* Delete proposal_v1.1.pdf

* Add files via upload

* Update .gitignore

* Update .gitignore

* Changed the folder name from binary to build, for later usage of BinaryProvider

* Edited the script 'samples.jl':
modified some print info.
Currently known bug: (maybe) inappropriate usage of 'convert'

ERROR: LoadError: ArgumentError: cannot take the CPU address of a GPU buffer
Stacktrace:
 [1] convert(::Type{Ptr{Float32}}, ::CUDAdrv.Mem.DeviceBuffer) at /home/jerry/.julia/packages/CUDAdrv/3cR2F/src/memory.jl:83
 [2] unsafe_convert(::Type{Ptr{Float32}}, ::CUDAdrv.Mem.DeviceBuffer) at /home/jerry/.julia/packages/CUDAdrv/3cR2F/src/memory.jl:32
 [3] unsafe_convert(::Type{PtrOrCuPtr{Float32}}, ::CUDAdrv.Mem.DeviceBuffer) at /home/jerry/.julia/packages/CUDAdrv/3cR2F/src/pointer.jl:115
 [4] magmaSgesvd(::Int64, ::Int64, ::Int64, ::Int64, ::CuArray{Float32,2}, ::Int64, ::CuArray{Float32,2}, ::CuArray{Float32,2}, ::Int64, ::CuArray{Float32,2}, ::Int64, ::CuArray{Float32,1}, ::Int64, ::Array{Int32,1}) at /home/jerry/MAGMA.jl-1/samples/samples.jl:45
 [5] gesvd!(::Int64, ::Int64, ::CuArray{Float32,2}, ::Int64, ::Int64, ::Int64) at /home/jerry/MAGMA.jl-1/samples/samples.jl:166
 [6] top-level scope at none:0
in expression starting at /home/jerry/MAGMA.jl-1/samples/samples.jl:191

* This is just a prototype for simply testing the compatibility.
Will be re-organized and heavily polished later.

* Constructed the hierarchy of source codes

* Simply introduced how to utilize current NAIVE test.jl. Will improve later.

* Turned the Utilities part into a module

* Cleaned the testing prototype and correct some errors in the lowest wrappers

* Constructed the tests hierarchy and encoded the original test.jl file.

* Corrected the path. There shouldn't be spaces and uppercases.

* Change the data types "Float64" and "Float32" to standard alias "Cdouble" and "Cfloat"

* Change the data types "Float64" and "Float32" to standard alias "Cdouble" and "Cfloat"

* Changed the path names to much shorter version. Also edited the test path

* Edited the README

* Slightly altered the testing logic so that it looks more natural.

* Edited the README.md

* Corrected the README.md

* Deleted useless samples

* deleted useless test.jl in the test/ folder

* Polished some usage

* Corrected the name of Sgesvd testing.

* polished testing files

* Changed to test_broken

* Deleted the [deps] on Revise which shouldn't exist.

* REMOVE unnecessary modules and DELETE redundant files.

* ADD a file 'gesvd2.jl' using @eval to generate wrappers, CHANGE tests.

* POLISH gesvd2.jl and FIX the test for sgesvd. Now the two tests passed.